# Generated by Django 4.2.1 on 2023-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
