# Generated by Django 4.2.1 on 2023-06-22 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negrito', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', models.CharField(max_length=100)),
                ('cor', models.CharField(choices=[('warning', 'Amarelo'), ('danger', 'Vermelho'), ('info', 'Azul'), ('secondary', 'Preto')], default='warning', max_length=40)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='lavib.pa@gmail.com', max_length=254)),
                ('telefone', models.CharField(default='91991487970', max_length=18)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imagem', models.ImageField(upload_to='main/images/cursos')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('professor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vagas', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='main/images/diretoria')),
                ('ano', models.PositiveSmallIntegerField(default=2023)),
                ('lattes', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao_curta', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('mensagem_comprovante', models.CharField(blank=True, default='Não se atrase!', max_length=150, null=True)),
                ('imagem', models.ImageField(upload_to='main/images/eventos')),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vagas', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('carga_horaria', models.PositiveSmallIntegerField(default=0)),
                ('convidados', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('cursos', models.ManyToManyField(blank=True, to='main.curso', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Index_Carousel_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/images/indexCarousel')),
                ('image_description', models.CharField(default='', max_length=100)),
                ('caption_title', models.CharField(default='', max_length=50)),
                ('caption_text', models.CharField(default='', max_length=250)),
                ('link', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'Index_Carousel_Item',
                'verbose_name_plural': 'Index_Carousel_Items',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('imagem', models.ImageField(upload_to='main/images/patrocinadores')),
                ('link', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='QR_Code_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='main/images')),
            ],
            options={
                'verbose_name': 'QRCode',
                'verbose_name_plural': 'QRCode',
            },
        ),
        migrations.CreateModel(
            name='Sobre_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Sobre_Text',
                'verbose_name_plural': 'Sobre_Texts',
            },
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero_inscricao', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefone', models.CharField(default='', max_length=18)),
                ('graduacao', models.CharField(blank=True, max_length=50, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_inscricao', models.DateTimeField(auto_now_add=True)),
                ('pagamento_confirmado', models.BooleanField(default=False)),
                ('data_limite_pagamento', models.DateTimeField(blank=True, null=True)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='main/images/comprovantes')),
                ('cursos', models.ManyToManyField(blank=True, to='main.curso')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='main.evento')),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
                'unique_together': {('email', 'evento')},
            },
        ),
    ]
