# Generated by Django 4.2.1 on 2023-05-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao_curta', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('mensagem_comprovante', models.CharField(blank=True, default='Não se atrase!', max_length=150, null=True)),
                ('imagem', models.ImageField(upload_to='main/images/eventos')),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vagas', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('carga_horaria', models.PositiveSmallIntegerField(default=0)),
                ('convidados', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Index_Carousel_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/images/indexCarousel')),
                ('image_description', models.CharField(default='', max_length=100)),
                ('caption_title', models.CharField(default='', max_length=50)),
                ('caption_text', models.CharField(default='', max_length=250)),
                ('link', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'Index_Carousel_Item',
                'verbose_name_plural': 'Index_Carousel_Items',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sobre_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Sobre_Text',
                'verbose_name_plural': 'Sobre_Texts',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscricao', models.PositiveSmallIntegerField(editable=False)),
                ('nome', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('telefone', models.CharField(default='', max_length=18)),
                ('curso', models.CharField(blank=True, max_length=50, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='main.evento')),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
                'unique_together': {('email', 'evento')},
            },
        ),
    ]
