# Generated by Django 4.2.1 on 2023-06-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lavib_info_redessocias_delete_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redes_Sociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('icone', models.FileField(upload_to='main/images/RedesSociais')),
                ('url', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'Redes Sociais',
            },
        ),
        migrations.DeleteModel(
            name='RedesSocias',
        ),
        migrations.AddField(
            model_name='alerta',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
