# Generated by Django 4.2.1 on 2023-08-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_redes_sociais_delete_redessocias_alerta_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='lavib.pa@gmail.com', max_length=254)),
                ('telefone', models.CharField(default='91991487970', max_length=18)),
                ('qrcode_pagamento', models.ImageField(upload_to='main/images')),
                ('sobre_nos', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configurações',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.DeleteModel(
            name='LAVIB_Info',
        ),
        migrations.AlterModelOptions(
            name='index_carousel_item',
            options={'verbose_name': 'Item do Carousel da Página Inicial', 'verbose_name_plural': 'Itens do Carousel da Página Inicial'},
        ),
        migrations.AlterModelOptions(
            name='redes_sociais',
            options={'verbose_name': 'Redes Sociais', 'verbose_name_plural': 'Redes Sociais'},
        ),
        migrations.AlterModelTable(
            name='index_carousel_item',
            table=None,
        ),
    ]
