# Generated by Django 4.2.5 on 2023-09-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_settings_delete_lavib_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_carousel_item',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='settings',
            name='chave_pix',
            field=models.CharField(default='91988458968', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='nome_conta',
            field=models.CharField(default='Leonardo Matheus de Abreu Costa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='data_hora_inscricao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Inscrição:'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='data_limite_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data limite de pagamento:'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='graduacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cursando:'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='instituicao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instituição:'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='nome',
            field=models.CharField(default='', max_length=80, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='numero_inscricao',
            field=models.PositiveSmallIntegerField(verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='pagamento_confirmado',
            field=models.BooleanField(default=False, verbose_name='Pagou?'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='telefone',
            field=models.CharField(default='', max_length=18, verbose_name='Telefone:'),
        ),
    ]
