# Generated by Django 4.2.5 on 2023-09-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_index_carousel_item_options_settings_chave_pix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupom', models.CharField(max_length=25, verbose_name='Cupom')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Desconto',
                'verbose_name_plural': 'Descontos',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='descontos',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.desconto', verbose_name='Descontos'),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='desconto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.desconto', verbose_name='Desconto'),
        ),
    ]
