# Generated by Django 4.2.5 on 2023-09-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_desconto_evento_descontos_inscrito_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='quantidade',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Quantidade:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descontos',
            field=models.ManyToManyField(blank=True, default=None, to='main.desconto', verbose_name='Descontos'),
        ),
    ]
