# Generated by Django 4.0.6 on 2023-10-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_redes_sociais_icone_alter_curso_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_hora_final',
            field=models.DateTimeField(default='2023-10-30 17:00:00', verbose_name='Data e hora do fim do evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index_carousel_item',
            name='target_blank',
            field=models.BooleanField(default=True, verbose_name='Abrir em outra guia?'),
        ),
    ]
