# Generated by Django 4.2.5 on 2023-10-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_index_carousel_item_target_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_hora_final',
            field=models.DateTimeField(default='2023-09-28 17:00:00', verbose_name='Data e hora do fim do evento'),
            preserve_default=False,
        ),
    ]
