# Generated by Django 4.0.6 on 2023-10-05 21:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_evento_data_hora_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='plano_de_fundo',
            field=models.FileField(blank=True, null=True, upload_to='main/images', validators=[main.models.Settings.validate_media_file], verbose_name='Plano de fundo do site'),
        ),
    ]
