# Generated by Django 4.2.5 on 2023-10-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_evento_data_hora_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='plano_de_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='main/images', verbose_name='Plano de fundo do site'),
        ),
    ]
