# Generated by Django 4.2.5 on 2023-10-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_settings_plano_de_fundo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='Nome')),
                ('foto', models.ImageField(upload_to='main/images/participantes', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.RemoveField(
            model_name='evento',
            name='convidados',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='professor',
        ),
        migrations.AddField(
            model_name='evento',
            name='palestrantes',
            field=models.ManyToManyField(blank=True, to='main.participante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ManyToManyField(blank=True, to='main.participante'),
        ),
    ]
