# Generated by Django 4.2.5 on 2023-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_participante_remove_evento_convidados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='descricao',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participante',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
