# Generated by Django 4.2.5 on 2023-10-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_participante_descricao_alter_participante_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='data_limite_pagamento',
        ),
        migrations.AddField(
            model_name='inscrito',
            name='indicacao',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Quem indicou?'),
        ),
    ]
